language: php

php:
  - 7
  - 7.1
  - 7.2

env:
  - PHPUNIT_VERSION=6.0
  - PHPUNIT_VERSION=7.0

matrix:
  exclude:
    - php: 7
      env: PHPUNIT_VERSION=7.0

sudo: false

install:
  - composer require phpunit/phpunit:^$PHPUNIT_VERSION --update-no-dev --no-interaction --prefer-dist --no-progress --no-suggest --update-with-all-dependencies
  - travis_retry composer install --dev --no-interaction --prefer-dist

script:
  - composer cs-check
  - composer test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
