language: php

php:
  - 5.6
  - 7
  - 7.1
  - 7.2

env:
  - PHPUNIT_VERSION=4.0
  - PHPUNIT_VERSION=5.0

sudo: false

install:
  - composer require phpunit/phpunit:^$PHPUNIT_VERSION --update-no-dev --no-interaction --prefer-dist --no-progress --no-suggest --update-with-all-dependencies
  - travis_retry composer install --dev --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit
